### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by vitusbenson** [taohan10200/CRA5#1]
Hi All,

I just saw your preprint, super cool work!! I was wondering when you'll release the full CRA5? I'd like to run some experiments :)

All the best,
Vitus

**Comment by taohan10200** [comment]
Hi, [vitusbenson](https://github.com/vitusbenson)

Thanks for your attention. 

Due to the busy schedule in May, we plan to release the code and data later in this month.

Best
Tao

**Comment by jacobbieker** [comment]
Is there any update on this? Am quite interested in trying it out!

**Comment by taohan10200** [comment]
@jacobbieker @vitusbenson CRA5 now is available. Please look at here https://github.com/taohan10200/CRA5/issues#issuecomment-2326937679.
