### ISSUE TITLE
Error: No module named 'cra5'

### ISSUE THREAD

**Issue by Sardingfish** [taohan10200/CRA5#3]
Hi
There is something wrong with setup.py, It only creates the dist-info but not the module cra5 in the site-packages path after installation. It resulted in the error: ModuleNotFoundError: No module named 'cra5'

**Comment by taohan10200** [comment]
Thanks for your attention. 

There are some bugs when installing with pip. We will try to figure out it. Alternatively, you can install from the source code:
```bash
git https://github.com/taohan10200/CRA5
cd CRA5
python setup.py install 
````
