### ISSUE TITLE
Missing states on OneDrive

### ISSUE THREAD

**Issue by gerome-andry** [taohan10200/CRA5#5]
Hello!

Thank you a lot for the initiative of this package/paper! I really appreciate your efforts to make weather research easier for everyone.

I noticed that some years (e.g. 1996-2000) are missing on the Onedrive you provided! 

It also seems that, after 2014, years have unconsistent gaps in their states (missing sometimes almost the full year). 

Have you noticed it? Is a fix planned?

I exactly fit your purpose, I would like to play with the compressed dataset without playing with hr data as I don't have sufficient hardware to work in pixel space!

Thank you in advance for your answer.

**Comment by taohan10200** [comment]
Hello, 

Thanks for your attention. 

We also notice that the compressed CRA5 dataset is not completed yet.  We have a plan to fix the missing time. However, the schedule now is very busy, and we plan to make it done in the following two weeks. 

I suggested you can use some completed yrs to do some preliminary experiments. Once we fix, we will comment here to notice you.

Thanks,
Tao

**Comment by gerome-andry** [comment]
Perfect! I will do that.

Thanks a lot.

**Comment by taohan10200** [comment]
@gerome-andry

Sorry for late update!
 Hourly CRA5 dataset from 1979-2023 has been completely upadated to OneDrive, Fell free to use it.
 
 Best,
 Tao
