### ISSUE TITLE
arbitrary number of input

### ISSUE THREAD

**Issue by px39n** [taohan10200/CRA5#6]
Hi may i ask is that support (or any suggestions) arbitrary intput of time/channels like 4, 16, 24 since the time slice in real time is unfixed.

net = vaeformer_pretrained(quality=268, pretrained=True).eval().to(device)
x = torch.rand(1,24, 721,1440).to(device) #This is a proxy weather data. It actually should be a 
print(x.shape)
with torch.no_grad():
    out_net = net.compress(x)

**Comment by px39n** [comment]
OR arbitary input of image size? could you please provide a minimal code space for reference

**Comment by taohan10200** [comment]
Hi, 

If you are using the pre-trained model, the input size and the number of weather variables must be aligned with it pre-trained wights.

However, if you are just using the network to train on your own data. You can change the network parameters to fit your input size and number of channels. The specific configuration of the network is in [vaeformer.py](https://github.com/taohan10200/CRA5/blob/main/cra5/models/vaeformer/vaeformer.py)

**Comment by px39n** [comment]
> Hi,
> 
> If you are using the pre-trained model, the input size and the number of weather variables must be aligned with it pre-trained wights.
> 
> However, if you are just using the network to train on your own data. You can change the network parameters to fit your input size and number of channels. The specific configuration of the network is in [vaeformer.py](https://github.com/taohan10200/CRA5/blob/main/cra5/models/vaeformer/vaeformer.py)

Thx, Good job BTW.
